### ISSUE TITLE
Deprecation Notice: The callback Barryvdh\Composer\CleanupPlugin::onPostPackageInstall...

### ISSUE THREAD

**Issue by daiplusplus** [barryvdh/laravel-vendor-cleanup#22]
I'm using `Composer version 1.6.2 2018-01-05 15:28:41`.

I get this depreciation notice when running `composer install`:

> Deprecation Notice: The callback `Barryvdh\Composer\CleanupPlugin::onPostPackageInstall` declared at `foo\vendor\barryvdh\composer-cleanup-plugin\src\CleanupPlugin.php` accepts a `Composer\Script\PackageEvent` but post-package-install events use a `Composer\Installer\PackageEvent` instance.  
> Please adjust your type hint accordingly, see https://getcomposer.org/doc/articles/scripts.md#event-classes in `phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php:322`

**Comment by barryvdh** [comment]
This package is deprecated.
